service: slack-orbo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

package:
  exclude:
  - node_modules/**/*
  include:
    handler.ts

functions:
  slack:
    handler: target/handler.slack
    events:
    - http:
        path: ''
        method: post

plugins:
- serverless-offline